<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add" tests="3" skipped="0" failures="2" errors="0" timestamp="2024-02-26T09:14:51" hostname="DESKTOP-CR4IAKN" time="0.012">
  <properties/>
  <testcase name="isEmpty_OnEmptyList_True" classname="ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add" time="0.007"/>
  <testcase name="add_Numbers1To5_AllNumbersAdded" classname="ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add" time="0.004">
    <failure message="java.lang.AssertionError: expected:&lt;5&gt; but was:&lt;6&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;5&gt; but was:&lt;6&gt;
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at ch.fhnw.algd2.collections.list.linkedlist.general.AbstractMyLinkedListTest.addNumbersToList(AbstractMyLinkedListTest.java:34)
	at ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add.add_Numbers1To5_AllNumbersAdded(A_MyLinkedListTest_Add.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
</failure>
  </testcase>
  <testcase name="add_AddDuplicates_AllNumbersAdded" classname="ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add" time="0.001">
    <failure message="java.lang.AssertionError: expected:&lt;6&gt; but was:&lt;7&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;6&gt; but was:&lt;7&gt;
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at ch.fhnw.algd2.collections.list.linkedlist.general.AbstractMyLinkedListTest.addNumbersToList(AbstractMyLinkedListTest.java:34)
	at ch.fhnw.algd2.collections.list.linkedlist.A_MyLinkedListTest_Add.add_AddDuplicates_AllNumbersAdded(A_MyLinkedListTest_Add.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
